import { Lead } from './types';

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Алексей Петров',
    company: 'SportLife Gym Network',
    email: 'a.petrov@sportlife.ru',
    phone: '+7 (495) 123-45-67',
    status: 'new',
    source: 'website',
    priority: 'high',
    value: 850000,
    notes: 'Сеть из 12 фитнес-клубов по Москве. Заинтересованы в поставке BLACKBORZ для баров при клубах.',
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-06-15T10:00:00Z',
    tags: ['фитнес', 'HoReCa', 'Москва'],
    contactPerson: 'Алексей Петров',
    region: 'Москва',
  },
  {
    id: '2',
    name: 'Мария Соколова',
    company: 'ТЦ Мега Белая Дача',
    email: 'm.sokolova@mega.ru',
    phone: '+7 (495) 234-56-78',
    status: 'contacted',
    source: 'referral',
    priority: 'high',
    value: 1200000,
    notes: 'Менеджер по закупкам продуктов питания. Ищут новый энергетик для фудкортов ТЦ.',
    createdAt: '2026-06-12T09:00:00Z',
    updatedAt: '2026-06-16T14:00:00Z',
    tags: ['ритейл', 'фудкорт', 'MO'],
    contactPerson: 'Мария Соколова',
    region: 'Московская область',
  },
  {
    id: '3',
    name: 'Игорь Васильев',
    company: 'Delivery Club Logistics',
    email: 'i.vasiliev@dc-log.ru',
    phone: '+7 (812) 345-67-89',
    status: 'qualified',
    source: 'event',
    priority: 'medium',
    value: 2500000,
    notes: 'Директор по закупкам. Познакомились на выставке ProductEXPO 2026. Нужна поставка для сотрудников-курьеров.',
    createdAt: '2026-06-10T11:00:00Z',
    updatedAt: '2026-06-17T09:00:00Z',
    aiScore: 82,
    aiAnalysis: 'Высокий потенциал. Крупный корпоративный клиент с постоянной потребностью.',
    tags: ['корпоратив', 'логистика', 'СПБ'],
    contactPerson: 'Игорь Васильев',
    region: 'Санкт-Петербург',
  },
  {
    id: '4',
    name: 'Дарья Новикова',
    company: 'X5 Retail Group',
    email: 'd.novikova@x5.ru',
    phone: '+7 (495) 456-78-90',
    status: 'proposal',
    source: 'cold_call',
    priority: 'high',
    value: 5800000,
    notes: 'Категорийный менеджер по энергетикам. Рассматривают BLACKBORZ для листинга в Перекрёстке.',
    createdAt: '2026-06-05T08:00:00Z',
    updatedAt: '2026-06-18T08:00:00Z',
    aiScore: 91,
    aiAnalysis: 'Ключевой клиент. Листинг в X5 даст национальный охват.',
    aiSummary: 'X5 — крупнейший ритейлер РФ. Потенциальный листинг в 1000+ магазинов Перекрёсток. Требуется согласование цены и маркетинговой поддержки.',
    tags: ['ключевой', 'ритейм', 'федеральный'],
    contactPerson: 'Дарья Новикова',
    region: 'Федеральный',
  },
  {
    id: '5',
    name: 'Сергей Кузнецов',
    company: 'Киберспорт Арена Pro',
    email: 's.kuznetsov@esports-arena.ru',
    phone: '+7 (495) 567-89-01',
    status: 'won',
    source: 'social',
    priority: 'medium',
    value: 320000,
    notes: 'Сеть киберспортивных арен. Подписан контракт на 6 месяцев.',
    createdAt: '2026-05-20T12:00:00Z',
    updatedAt: '2026-06-01T10:00:00Z',
    aiScore: 78,
    tags: ['киберспорт', 'gaming', 'Москва'],
    contactPerson: 'Сергей Кузнецов',
    region: 'Москва',
  },
  {
    id: '6',
    name: 'Анна Морозова',
    company: 'Premium Hotels Collection',
    email: 'a.morozova@phc.ru',
    phone: '+7 (495) 678-90-12',
    status: 'contacted',
    source: 'referral',
    priority: 'medium',
    value: 680000,
    notes: 'Сеть 4* и 5* отелей. Интересуются размещением BLACKBORZ в минибарах и лобби-барах.',
    createdAt: '2026-06-13T15:00:00Z',
    updatedAt: '2026-06-17T11:00:00Z',
    tags: ['HoReCa', 'отели', 'премиум'],
    contactPerson: 'Анна Морозова',
    region: 'Москва',
  },
  {
    id: '7',
    name: 'Павел Орлов',
    company: 'Festival Planet',
    email: 'p.orlov@festplanet.ru',
    phone: '+7 (903) 789-01-23',
    status: 'new',
    source: 'social',
    priority: 'low',
    value: 450000,
    notes: 'Организатор музыкальных фестивалей. Хотят BLACKBORZ как партнёра для летних мероприятий.',
    createdAt: '2026-06-17T16:00:00Z',
    updatedAt: '2026-06-17T16:00:00Z',
    tags: ['события', 'фестиваль', 'BTL'],
    contactPerson: 'Павел Орлов',
    region: 'Россия',
  },
  {
    id: '8',
    name: 'Елена Смирнова',
    company: 'AutoDrive Fleet',
    email: 'e.smirnova@autodrive.ru',
    phone: '+7 (812) 890-12-34',
    status: 'lost',
    source: 'cold_call',
    priority: 'low',
    value: 180000,
    notes: 'Не прошли по цене. Клиент выбрал конкурента.',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-14T12:00:00Z',
    aiScore: 35,
    tags: ['авто', 'СПБ', 'потеряно'],
    contactPerson: 'Елена Смирнова',
    region: 'Санкт-Петербург',
  },
];

export const KANBAN_COLUMNS = [
  { id: 'new' as const, title: 'Новые', color: '#6366f1', bgColor: 'bg-indigo-500/10', borderColor: 'border-indigo-500/30' },
  { id: 'contacted' as const, title: 'Контакт', color: '#3b82f6', bgColor: 'bg-blue-500/10', borderColor: 'border-blue-500/30' },
  { id: 'qualified' as const, title: 'Квалификация', color: '#f59e0b', bgColor: 'bg-amber-500/10', borderColor: 'border-amber-500/30' },
  { id: 'proposal' as const, title: 'Предложение', color: '#8b5cf6', bgColor: 'bg-purple-500/10', borderColor: 'border-purple-500/30' },
  { id: 'won' as const, title: 'Выиграно', color: '#10b981', bgColor: 'bg-emerald-500/10', borderColor: 'border-emerald-500/30' },
  { id: 'lost' as const, title: 'Проиграно', color: '#ef4444', bgColor: 'bg-red-500/10', borderColor: 'border-red-500/30' },
];
